{% set githash_version = "bac520839ff5ed2e2b648ed540bd9ec45edbccbc" %}
{% set version = "0.0.0.2024.11.12." + githash_version[:7] %}

package:
  name: webgpu-headers
  version: {{ version }}

source:
  url: https://github.com/webgpu-native/webgpu-headers/archive/{{ githash_version }}.tar.gz
  sha256: 623444b066f2bc048bf60235bbf4e1c9eeb72ab22e2b043f1ca2b5d229863bc8

build:
  noarch: generic
  number: 0

requirements:
  run:
    - __unix  # [unix]
    - __win   # [win]

test:
  commands:
    - test -f ${PREFIX}/include/webgpu.h   # [unix]
    - if not exist %PREFIX%\\Library\\include\\webgpu.h exit 1  # [win]

about:
  home: https://github.com/webgpu-native/webgpu-headers
  summary: WebGPU Headers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
